config/routes.rb
Rails.application.routes.draw do
  resources :businesses
  resources :maps
  resources :midpoints
  resources :addresses

  root 'map#new'

end

app/models/midpoint.rb
# == Schema Information
#
# Table name: midpoints
#
#  id             :integer          not null, primary key
#  midpoint       :float
#  address_1      :integer
#  address_2      :integer
#  search_results :integer
#  created_at     :datetime         not null
#  updated_at     :datetime         not null
#

class Midpoint < ActiveRecord::Base
end

app/controllers/midpoints_controller.rb
class MidpointsController < ApplicationController
  before_action :set_midpoint, only: [:show, :edit, :update, :destroy]

  # GET /midpoints
  # GET /midpoints.json
  def index
    @midpoints = Midpoint.all
  end

  # GET /midpoints/1
  # GET /midpoints/1.json
  def show
  end

  # GET /midpoints/new
  def new
    @midpoint = Midpoint.new
  end

  # GET /midpoints/1/edit
  def edit
  end

  # POST /midpoints
  # POST /midpoints.json
  def create
    @midpoint = Midpoint.new(midpoint_params)

    respond_to do |format|
      if @midpoint.save
        format.html { redirect_to @midpoint, notice: 'Midpoint was successfully created.' }
        format.json { render :show, status: :created, location: @midpoint }
      else
        format.html { render :new }
        format.json { render json: @midpoint.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /midpoints/1
  # PATCH/PUT /midpoints/1.json
  def update
    respond_to do |format|
      if @midpoint.update(midpoint_params)
        format.html { redirect_to @midpoint, notice: 'Midpoint was successfully updated.' }
        format.json { render :show, status: :ok, location: @midpoint }
      else
        format.html { render :edit }
        format.json { render json: @midpoint.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /midpoints/1
  # DELETE /midpoints/1.json
  def destroy
    @midpoint.destroy
    respond_to do |format|
      format.html { redirect_to midpoints_url, notice: 'Midpoint was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_midpoint
      @midpoint = Midpoint.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def midpoint_params
      params.require(:midpoint).permit(:midpoint, :address_1, :address_2)
    end
end

app/helpers/midpoints_helper.rb
module MidpointsHelper
end

app/views/midpoints/_form.html.erb
<%= simple_form_for(@midpoint) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :midpoint %>
    <%= f.input :address_1 %>
    <%= f.input :address_2 %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/midpoints/edit.html.erb
<h1>Editing Midpoint</h1>

<%= render 'form' %>

<%= link_to 'Show', @midpoint %> |
<%= link_to 'Back', midpoints_path %>

app/views/midpoints/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Midpoints</h1>

<table>
  <thead>
    <tr>
      <th>Midpoint</th>
      <th>Address 1</th>
      <th>Address 2</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @midpoints.each do |midpoint| %>
      <tr>
        <td><%= midpoint.midpoint %></td>
        <td><%= midpoint.address_1 %></td>
        <td><%= midpoint.address_2 %></td>
        <td><%= link_to 'Show', midpoint %></td>
        <td><%= link_to 'Edit', edit_midpoint_path(midpoint) %></td>
        <td><%= link_to 'Destroy', midpoint, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Midpoint', new_midpoint_path %>

app/views/midpoints/new.html.erb
<h1>New Midpoint</h1>

<%= render 'form' %>

<%= link_to 'Back', midpoints_path %>

app/views/midpoints/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Midpoint:</strong>
  <%= @midpoint.midpoint %>
</p>

<p>
  <strong>Address 1:</strong>
  <%= @midpoint.address_1 %>
</p>

<p>
  <strong>Address 2:</strong>
  <%= @midpoint.address_2 %>
</p>

<%= link_to 'Edit', edit_midpoint_path(@midpoint) %> |
<%= link_to 'Back', midpoints_path %>